AMP-78: Parse FastAPI 422 errors
Rev-AMP/frontend pull request #36
Opened 2021-04-05 20:31 UTC by ksdfg

This needs some serious testing, we're gonna need to go through all the pages

2021-04-06 13:47 UTC, akhilnarang requested changes

2021-04-06 13:47 UTC, akhilnarang commented on src/pages/users/components/UserModal.jsx
> +            // } else {
Remove pura code? Any reason for just commenting?

2021-04-06 15:19 UTC, aniket-spidey commented on src/services/http-client.js
> +};
I don't get this. Is this incomplete?

2021-04-08 16:38 UTC, PranavBakre submitted a review, later dismissed
More or less looks good to me. Someone just check my commit once

2021-04-08 16:48 UTC, PranavBakre approved these changes

2021-04-09 05:39 UTC, akhilnarang approved these changes

2021-04-09 05:39 UTC, merged